Fix compilation of ready boolean checks
Compilation is currently failing with the error:
controllers/ironic_controller.go:506:27: undefined: ironicInspector
because ironicInspector is being accessed outside the block which
assigns it.

This change reworks the ready boolean checks to initialize them early
and change them in context.